# INCLUDES=./FRAMES/title.tex ./FRAMES/01-WHOIAM.tex 
INCLUDES=./01-WHOAMI/*.tex ./02-CurrentResearch/*.tex

MFSLides: main.tex ${INCLUDES}
	pdflatex main.tex
	#pdflatex main.tex

clean:
	rm *.out *.log *.aux
